/*
Package internal GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package internal

import (
	context "context"
)

type contextProvider struct{}

func ProviderFromContext(ctx context.Context) (Provider, bool) {
	if v, ok := ctx.Value(contextProvider{}).(Provider); ok {
		return v, true
	}
	return nil, false
}

func ProviderInjectContext(ctx context.Context, tpe Provider) context.Context {
	return context.WithValue(ctx, contextProvider{}, tpe)
}
