/*
Package encryption GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package encryption

import (
	context "context"

	jwk "github.com/octohelm/jwx/pkg/jwk"
)

func (v *Encrypter) Init(ctx context.Context) error {
	if value, ok := jwk.KeySetProviderFromContext(ctx); ok {
		v.keySetProvider = value
	}

	if err := v.afterInit(ctx); err != nil {
		return err
	}

	return nil
}
