/*
Package sign GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package sign

func (v *JWTSigner) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Issuer":
			return []string{
				"jwt token 签发方",
			}, true
		case "PrivateKey":
			return []string{
				"jwt 签发私钥 (base64 std encoding 格式)",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *JWTValidator) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "JwksEndpoint":
			return []string{}, true
		case "TTL":
			return []string{
				"过期时间",
			}, true

		}
		if doc, ok := runtimeDoc(&v.Validator, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (*ValidateOption) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
