// Code generated by gengo:injectable DO NOT EDIT.
package http

import (
	context "context"
	fmt "fmt"

	internal "github.com/octohelm/jwx/pkg/encryption/internal"
)

func (v *MiddlewareProvider) Init(ctx context.Context) error {
	if value, ok := internal.ProviderFromContext(ctx); ok {
		v.Provider = value
	} else {
		return fmt.Errorf("missing provider %T.Provider", v)
	}

	return nil
}
